/// The `mimic_genip` generator, as value objects.
///
/// [MimicGenIpConfig] holds what the command line states and derives
/// everything else: the build target, the SoC, the nextpnr pre-place script
/// and the `mimic.json` manifest. `bin/mimic_genip.dart` only parses arguments
/// into this class and prints the summary, so every derivation here is
/// reachable from a unit test.
library;

import 'dart:convert';
import 'dart:io';

import 'package:harbor/harbor.dart';
import 'package:rohd/rohd.dart';

import 'hw/sd_block_cache.dart' show sdCacheDefaultLines, sdCacheLinesValid;
import 'hw/sd_card_fsm.dart' show sdCardCidValueFor;
import 'regs.dart';
import 'sd_regs.dart';
import 'soc.dart';

/// The ROHD instance names of the USB line PHY submodules under [root].
///
/// [HarborUsbFsRx] and [HarborUsbFsTx] keep their instance name through
/// synthesis, so every flattened netlist cell of a PHY carries that name in
/// its hierarchical path. The nextpnr pre-place script matches on it.
/// Reading the name out of the elaborated design keeps the script correct
/// when a PHY instance is renamed. A hardcoded copy went stale once, and the
/// script then matched no cells.
Set<String> usbPhyInstanceNames(Module root) {
  final names = <String>{};
  void walk(Module module) {
    for (final sub in module.subModules) {
      if (sub is HarborUsbFsRx || sub is HarborUsbFsTx) {
        names.add(sub.uniqueInstanceName);
      }
      walk(sub);
    }
  }

  walk(root);
  return names;
}

/// Formats [items] as a Python tuple of strings.
String _pyTuple(List<String> items) {
  final quoted = items.map((s) => '"$s"').join(', ');
  return items.length == 1 ? '($quoted,)' : '($quoted)';
}

/// The nextpnr `--pre-place` script that keeps the USB line PHY beside the
/// USB pads, written to `support/nextpnr/constraints.py`.
///
/// Harbor's generated Makefile passes the file to nextpnr with `--pre-place`
/// when it is there, so no Makefile edit is necessary.
///
/// [padCells] are the top-level pad names to build the region around.
/// [phyPatterns] are the hierarchical-path fragments of the PHY cells to hold
/// in that region. Both come from the design, so a rename cannot make the
/// script match the wrong cells.
String usbPreplacePy({
  required List<String> padCells,
  required List<String> phyPatterns,
}) =>
    '''
# Pre-place: keep the USB line PHY logic next to the USB pads.
#
# GENERATED by mimic_genip. Do not edit.
#
# The D+/D- paths between the pads and the PHY must have a similar
# length. A flip-flop far from its pad gives a different routing delay
# for each half of the pair, so a differential edge arrives skewed.
# GregDavill's foboot uses the same method.
#
# The script finds the pads and the die size itself:
#  * Each pad cell holds its site in a BEL attribute, for example
#    "X72/Y47/PIOD". getBelLocation turns that into x and y.
#  * The die size comes from the largest bel coordinates.
# The region is the box around the pads, made larger by MARGIN and
# clamped to the die. Nothing here is specific to one board, one
# package, or one FPGA family.
#
# MARGIN must give the region more space than the matched cells need.
# The line level serialiser and deserialiser hold more than 800 cells,
# and a box that is too small makes nextpnr stop with "Unable to find
# legal placement for all cells" even when the whole die is nearly
# empty. Give the region room and let the placer use it.

import re
import sys

PAD_CELLS = ${_pyTuple(padCells)}
PHY_PATTERNS = ${_pyTuple(phyPatterns)}
MARGIN = 16

_SITE = re.compile(r"^X(\\d+)/Y(\\d+)/")

# Die size.
max_x = 0
max_y = 0
for bel in ctx.getBels():
    m = _SITE.match(str(bel))
    if m:
        max_x = max(max_x, int(m.group(1)))
        max_y = max(max_y, int(m.group(2)))

# Pad positions.
xs = []
ys = []
for kv in ctx.cells:
    name = str(kv.first)
    if not any(p in name for p in PAD_CELLS):
        continue
    bel = None
    for attr in kv.second.attrs:
        if str(attr.first) == "BEL":
            bel = str(attr.second)
            break
    if bel is None or not _SITE.match(bel):
        continue
    loc = ctx.getBelLocation(bel)
    xs.append(loc.x)
    ys.append(loc.y)

if not xs:
    raise Exception(
        "pre-place found no USB pads. It looked for cells named %s that have "
        "a BEL attribute. Check the pad port names." % (PAD_CELLS,)
    )

x0 = max(0, min(xs) - MARGIN)
y0 = max(0, min(ys) - MARGIN)
x1 = min(max_x, max(xs) + MARGIN)
y1 = min(max_y, max(ys) + MARGIN)

ctx.createRectangularRegion("usb_phy", x0, y0, x1, y1)

phy_count = 0
for kv in ctx.cells:
    name = str(kv.first)
    if any(p in name for p in PHY_PATTERNS):
        ctx.constrainCellToRegion(name, "usb_phy")
        phy_count += 1

sys.stderr.write(
    "pre-place: die X0-%d Y0-%d, pads x=%s y=%s, region X%d-%d Y%d-%d, "
    "%d PHY cells\\n"
    % (max_x, max_y, sorted(set(xs)), sorted(set(ys)), x0, x1, y0, y1,
       phy_count)
)

if phy_count == 0:
    raise Exception(
        "pre-place matched no PHY cells with patterns %s. The instance names "
        "changed. A silent no-op gives skewed pads, so this is fatal."
        % (PHY_PATTERNS,)
    )
''';

/// The `mimic.json` manifest the host runtime reads.
///
/// The snake_case keys of [toJson] are a CONTRACT with the Zig runtime: they
/// are the field names of `runtime/lib/mimic/manifest.zig` `Manifest`, which
/// parses them one for one. Rename a key here and the runtime stops parsing
/// the file it is given.
class MimicManifest {
  /// The generated SoC name, which is also the top module name.
  final String name;

  /// Interface version as a dotted string, e.g. "1.0.0".
  final String interfaceVersion;

  /// The value the VERSION CSR reads: major << 16 | minor << 8 | patch.
  final int versionReg;

  /// USB idVendor (16-bit).
  final int idVendor;

  /// USB idProduct (16-bit).
  final int idProduct;

  /// Host cache size in 512-byte blocks.
  final int cacheBlocks;

  /// How the device serves the SD card. One of
  /// [MimicGenIpConfig.supportedSdModes].
  final String sdMode;

  /// Base address of the CSR window inside the SoC map.
  final int csrBase;

  /// The transport the bitstream exposes. One of
  /// [MimicGenIpConfig.supportedTransports].
  final String transport;

  const MimicManifest({
    required this.name,
    required this.interfaceVersion,
    required this.versionReg,
    required this.idVendor,
    required this.idProduct,
    required this.cacheBlocks,
    required this.sdMode,
    required this.csrBase,
    required this.transport,
  });

  /// The manifest as the runtime's `Manifest` struct reads it. Key order
  /// follows the struct so a person can compare the two side by side.
  Map<String, Object?> toJson() => {
    'name': name,
    'interface_version': interfaceVersion,
    'version_reg': versionReg,
    'vid': idVendor,
    'pid': idProduct,
    'cache_blocks': cacheBlocks,
    'sd_mode': sdMode,
    'csr_base': csrBase,
    'transport': transport,
  };

  /// [toJson] as the indented text written to `mimic.json`.
  String toJsonString() => const JsonEncoder.withIndent('  ').convert(toJson());
}

/// The manufacture date the card reports in the MDT field of its CID.
///
/// The SD CID holds the year after [sdCidMdtFirstYear] in 8 bits and the
/// month in 4 bits, so the field has MONTH granularity and no day at all.
/// This class holds exactly what the field holds and nothing more.
///
/// [resolve] states the order the generator reads the date in. All three
/// levels stay, so no build can make a card with no date:
///   1. `--manufacture-date`, which a caller names.
///   2. `SOURCE_DATE_EPOCH`, the reproducible-build environment variable.
///   3. the clock.
///
/// Level 2 is for a person who runs the generator inside a plain nix build
/// with no flag. The nix expressions of this repository do NOT rely on it:
/// nix stdenv sets `SOURCE_DATE_EPOCH` to 1980-01-01, so a build that let
/// level 2 answer would ship a card that reports 1980. They pass
/// `--manufacture-date` instead, and level 1 wins over level 2.
///
/// A `SOURCE_DATE_EPOCH` the MDT field cannot hold does NOT stop the build.
/// nix stdenv sets that variable to 1980-01-01, which the field cannot
/// express, and the point of the three levels is that no build can make a
/// card with no date. So level 2 STANDS ASIDE for a date out of range and
/// level 3, the clock, answers. The generator says on stderr that it did
/// this, so the date is never quietly wrong.
///
/// A date the CALLER names with `--manufacture-date` is still refused when
/// the field cannot hold it. A caller who names a date means it, and a
/// silent move to another year would be a lie. Only the environment, which
/// nobody set for this purpose, stands aside.
class MimicManufactureDate {
  /// Four-digit year. [sdCid] checks it against the MDT field.
  final int year;

  /// Month, 1 to 12. [sdCid] checks it against the MDT field.
  final int month;

  const MimicManufactureDate(this.year, this.month);

  /// The date a build that names none gets. It is the date [sdCid] itself
  /// defaults to, so the two cannot drift apart.
  static const MimicManufactureDate fallback = MimicManufactureDate(
    sdCidDefaultManufactureYear,
    sdCidDefaultManufactureMonth,
  );

  /// The name of the reproducible-build environment variable of level 2.
  static const String sourceDateEpochVariable = 'SOURCE_DATE_EPOCH';

  /// What the `--manufacture-date` flag accepts, said in one line. Every
  /// message about a date the generator refused carries it.
  static String get formatHelp =>
      'YYYY-MM, from $sdCidMdtFirstYear-01 to $sdCidMdtLastYear-12. The MDT '
      'field of the CID holds the year after $sdCidMdtFirstYear in 8 bits '
      'and the month in 4 bits, so it has no day.';

  static final RegExp _yearMonth = RegExp(r'^(\d{4})-(\d{2})$');

  /// Reads a `YYYY-MM` string.
  ///
  /// The SHAPE is checked here and the RANGE is not: [sdCid] owns the range
  /// of every CID field, and a second copy of the limits here would be one
  /// more place to let them drift. A date with the right shape and a month
  /// of 13 therefore parses and throws later, out of [cidValue].
  factory MimicManufactureDate.parse(String spec) {
    final match = _yearMonth.firstMatch(spec.trim());
    if (match == null) {
      throw FormatException('A manufacture date is $formatHelp Got: "$spec".');
    }
    return MimicManufactureDate(
      int.parse(match.group(1)!),
      int.parse(match.group(2)!),
    );
  }

  /// The year and the month of [time]. The rest of [time] is dropped,
  /// because the MDT field cannot hold it.
  factory MimicManufactureDate.fromDateTime(DateTime time) =>
      MimicManufactureDate(time.year, time.month);

  /// Reads `SOURCE_DATE_EPOCH`, which is whole seconds since the Unix
  /// epoch, in UTC. UTC is what the variable is defined in, so a build in
  /// any time zone gives the same month.
  factory MimicManufactureDate.fromSourceDateEpoch(String seconds) {
    final value = int.tryParse(seconds.trim());
    if (value == null) {
      throw FormatException(
        '$sourceDateEpochVariable is whole seconds since the Unix epoch. '
        'Got: "$seconds".',
      );
    }
    return MimicManufactureDate.fromDateTime(
      DateTime.fromMillisecondsSinceEpoch(value * 1000, isUtc: true),
    );
  }

  /// The date the generator uses, in the order the class doc states.
  ///
  /// [flag] is the `--manufacture-date` value, or null when the caller
  /// named none. [environment] defaults to the real environment, and
  /// [now] to the real clock; a test gives both.
  static MimicManufactureDate resolve({
    String? flag,
    Map<String, String>? environment,
    DateTime? now,
  }) {
    if (flag != null && flag.trim().isNotEmpty) {
      return MimicManufactureDate.parse(flag);
    }
    final epoch =
        (environment ?? Platform.environment)[sourceDateEpochVariable];
    if (epoch != null && epoch.trim().isNotEmpty) {
      final fromEpoch = MimicManufactureDate.fromSourceDateEpoch(epoch);
      // A date the MDT field cannot hold makes level 2 stand aside, so the
      // clock answers. nix stdenv sets this variable to 1980-01-01, which
      // the field cannot express, and a build must still get a date.
      try {
        fromEpoch.validate();
        return fromEpoch;
      } on ArgumentError {
        stderr.writeln(
          'warning: $sourceDateEpochVariable gives $fromEpoch, which the CID '
          'cannot hold. Using the clock. $formatHelp',
        );
      }
    }
    return MimicManufactureDate.fromDateTime(now ?? DateTime.now());
  }

  /// The 128-bit CID register of a card made on this date.
  ///
  /// [sdCid] checks the year and the month, so this is also where a date
  /// the MDT field cannot express is refused. There is no copy of the
  /// limits in this class.
  BigInt get cidValue =>
      sdCardCidValueFor(manufactureYear: year, manufactureMonth: month);

  /// Throws when the MDT field cannot hold this date.
  ///
  /// The check is the BUILD of the register, through [cidValue]. A second
  /// copy of the field limits here would be one more place to let them
  /// drift from [sdCid], which owns them.
  void validate() => cidValue;

  /// The date in the shape [parse] reads.
  @override
  String toString() =>
      '${year.toString().padLeft(4, '0')}-'
      '${month.toString().padLeft(2, '0')}';

  @override
  bool operator ==(Object other) =>
      other is MimicManufactureDate &&
      other.year == year &&
      other.month == month;

  @override
  int get hashCode => Object.hash(year, month);
}

/// Everything the command line states, plus every derivation the generator
/// makes from it.
///
/// The pattern follows river's `RiverGenIpConfig`: the binary builds one of
/// these and calls [generateAll]. Nothing here reads the argument vector, so
/// a test can build any configuration directly.
class MimicGenIpConfig {
  /// SoC name, which is also the generated top module name.
  final String name;

  /// Board from harbor's [HarborBoard] catalog. It supplies the part, the
  /// package, the oscillator rate, the pin sites and the program command.
  /// Ignored when [targetSpec] is set.
  final String? boardName;

  /// The `vendor:device:package` escape hatch for a board not in the catalog.
  /// Overrides [boardName] when set.
  final String? targetSpec;

  /// `name=site` pin specs. Each one replaces the board catalog entry of the
  /// same name and leaves the others alone.
  final List<String> pinSpecs;

  /// Oscillator rate in Hz, or null to take the board's rate.
  final int? oscHz;

  /// Host transport. One of [supportedTransports].
  final String transport;

  /// SD data mode. One of [supportedSdModes].
  final String sdMode;

  /// Host cache size in 512-byte blocks (manifest only in phase 1).
  final int cacheBlocks;

  /// Number of lines in the BLOCK CACHE of the card, which is the store in
  /// the gateware that answers a read with no round trip at all.
  ///
  /// It is not [cacheBlocks]: that number is the host cache of the
  /// runtime, and this one is silicon. It must be a power of two, because
  /// the index of a direct mapped store is the low bits of the block
  /// address and any other count needs a divider in the lookup path.
  ///
  /// One line holds ONE 512-byte block, so 128 lines is 64 KiB and takes
  /// 32 block RAMs of the part plus one for the tags.
  final int cacheLines;

  /// USB idVendor.
  final int idVendor;

  /// USB idProduct.
  final int idProduct;

  /// USB serial number string, or null for no serial.
  final String? serialNumber;

  /// Build the control-only USB variant: EP0 enumeration with no bulk
  /// endpoints, for enumeration isolation.
  final bool enumerateOnly;

  /// The MDT date the card reports in its CID.
  ///
  /// `bin/mimic_genip.dart` calls [MimicManufactureDate.resolve], so the
  /// flag, then `SOURCE_DATE_EPOCH`, then the clock decide it. The default
  /// here is [MimicManufactureDate.fallback], because a `const` constructor
  /// cannot read a clock; every real build passes a resolved date.
  final MimicManufactureDate manufactureDate;

  /// The transports the generator can build. The Zig runtime's `Transport`
  /// enum holds the same set, so a value outside it stops the runtime at
  /// parse time.
  static const List<String> supportedTransports = ['usb'];

  /// The SD data modes the generator can build. The Zig runtime's `SdMode`
  /// enum holds the same set. `loopback` is reserved for a later phase.
  static const List<String> supportedSdModes = ['served'];

  const MimicGenIpConfig({
    this.name = 'MimicSoC',
    this.boardName,
    this.targetSpec,
    this.pinSpecs = const [],
    this.oscHz,
    this.transport = 'usb',
    this.sdMode = 'served',
    this.cacheBlocks = 8,
    this.cacheLines = sdCacheDefaultLines,
    this.idVendor = 0x1209,
    this.idProduct = 0x10C1,
    this.serialNumber,
    this.enumerateOnly = false,
    this.manufactureDate = MimicManufactureDate.fallback,
  });

  /// Checks the configuration. Throws [ArgumentError] on a value the
  /// generator cannot build.
  void validate() {
    if (!supportedTransports.contains(transport)) {
      throw ArgumentError(
        'Unsupported transport "$transport". Known: '
        '${supportedTransports.join(', ')}.',
      );
    }
    if (!supportedSdModes.contains(sdMode)) {
      throw ArgumentError(
        'Unsupported sd-mode "$sdMode". Known: '
        '${supportedSdModes.join(', ')}.',
      );
    }
    // Any count >= 0 is accepted. There is no upper limit check: yosys and
    // nextpnr are the authority on what fits.
    if (cacheBlocks < 0) {
      throw ArgumentError('cache-blocks must be >= 0, got $cacheBlocks');
    }
    // The block cache of the card is direct mapped, so the index is the
    // low bits of the block address. A count that is not a power of two
    // needs a modulo, and a modulo is a divider in the lookup path of the
    // SD clock domain. Say so here and not in a synthesis report.
    if (!sdCacheLinesValid(cacheLines)) {
      throw ArgumentError(
        'cache-lines must be a power of two, 2 or more, got $cacheLines',
      );
    }
    // The date goes through [sdCid], which owns the limits of every CID
    // field. The check is cheap and it stops the generator before it
    // elaborates anything.
    manufactureDate.validate();
  }

  /// The target this build really uses, named the way the caller named it.
  /// [targetSpec] wins over [boardName], which is the order [buildTarget]
  /// resolves them in, so the summary never reports a board that was
  /// overridden.
  String get targetDescription => targetSpec ?? boardName ?? '(no target)';

  /// The build target: the `--target` escape hatch when set, else the board
  /// catalog entry, with the `--pin` overrides merged in.
  HarborFpgaTarget buildTarget() => resolveMimicTarget(
    board: boardName,
    targetSpec: targetSpec,
    pinSpecs: pinSpecs,
    oscHz: oscHz,
  );

  /// The board catalog entry this build targets, or null on the `--target`
  /// escape hatch where the caller named a part and not a board.
  ///
  /// The SoC reads the board DEFINITION (not the board name) to decide
  /// whether the SD clock pad needs a clock buffer. See [buildMimicSoc].
  HarborBoard? get board {
    final n = boardName;
    if (targetSpec != null || n == null) return null;
    return HarborBoard.get(n);
  }

  /// Builds the elaborated SoC for [buildTarget].
  HarborSoC buildSoC() {
    validate();
    final target = buildTarget();
    return buildMimicSoc(
      name: name,
      target: target,
      board: board,
      oscHz: target.frequency,
      idVendor: idVendor,
      idProduct: idProduct,
      serialNumber: serialNumber,
      bulkEndpoints: !enumerateOnly,
      // The board build binds one bidirectional ball per USB line, so the SoC
      // owns the D+/D- pads and drives them with its own tristate buffers.
      ownPads: true,
      // The board has an LED, so give it the card activity light.
      activityLed: true,
      // The date of the BUILD reaches the CID here. See
      // [MimicManufactureDate] for the order the generator resolves it in.
      manufactureYear: manufactureDate.year,
      manufactureMonth: manufactureDate.month,
      // The line count of the block cache of the card. See [cacheLines].
      cacheLines: cacheLines,
    );
  }

  /// The manifest for this build.
  MimicManifest get manifest => MimicManifest(
    name: name,
    interfaceVersion: MimicRegValue.versionString,
    versionReg: MimicRegValue.version,
    idVendor: idVendor,
    idProduct: idProduct,
    cacheBlocks: cacheBlocks,
    sdMode: sdMode,
    csrBase: mimicCsrBase,
    transport: transport,
  );

  /// Builds the SoC and writes every generated artifact into [outputDir]: the
  /// harbor SoC package, the nextpnr pre-place script and the manifest.
  /// Returns the elaborated SoC so the caller can report on it.
  ///
  /// [outputDir] IS the flashable build. harbor emits the RTL, the constraint
  /// file, `synth.tcl` and a Makefile there with the SoC as the synthesis top,
  /// so `make` in that directory gives the bitstream. There is no board shim
  /// and no second build directory: harbor's power-on reset and the PLL lock
  /// gate replaced the shim's counter, and the board catalog names the pins.
  Future<HarborSoC> generateAll(Directory outputDir) async {
    final soc = buildSoC();
    await soc.generateAll(outputDir);
    writePreplaceScript(soc, outputDir);
    writeManifest(outputDir);
    return soc;
  }

  /// Writes `support/nextpnr/constraints.py`, the nextpnr `--pre-place`
  /// script that holds the USB line PHY in a region around the USB pads. That
  /// keeps the D+ and D- routing delays close to equal.
  ///
  /// harbor's generated Makefile gives the file to nextpnr with `--pre-place`
  /// through `$(wildcard support/nextpnr/constraints.py)`, so it must sit
  /// beside the Makefile and no Makefile edit is needed.
  ///
  /// Both the pad names and the PHY cell names come from the design: the pads
  /// are [mimicUsbPadPins], and the PHY names come out of the elaborated
  /// hierarchy.
  ///
  /// harbor writes the same file for its own pre-place contributors (an
  /// openXC7 DDR PHY, or a peripheral that provides a fragment). This APPENDS
  /// to what is already there, because a clobber would silently drop the
  /// contribution that ran first.
  void writePreplaceScript(HarborSoC soc, Directory outputDir) {
    final phyNames = usbPhyInstanceNames(soc).toList()..sort();
    if (phyNames.isEmpty) {
      throw StateError(
        'No HarborUsbFsRx or HarborUsbFsTx instance in the elaborated SoC. '
        'The nextpnr pre-place script would hold no cells, which gives skewed '
        'USB pads, so this is fatal.',
      );
    }
    final script = usbPreplacePy(
      padCells: mimicUsbPadPins,
      phyPatterns: [for (final n in phyNames) '.$n.'],
    );
    Directory('${outputDir.path}/support/nextpnr').createSync(recursive: true);
    final file = File('${outputDir.path}/support/nextpnr/constraints.py');
    final existing = file.existsSync() ? file.readAsStringSync() : '';
    file.writeAsStringSync(existing.isEmpty ? script : '$existing\n$script');
  }

  /// Writes `mimic.json`, the manifest the host runtime consumes.
  void writeManifest(Directory outputDir) {
    File('${outputDir.path}/mimic.json')
        .writeAsStringSync(manifest.toJsonString());
  }
}
